apiVersion: v1
kind: Pod
metadata:
  name: newrelic-exporter
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9112'
spec:
  containers:
  - name: newrelic-exporter
    image: wreckedreddocker/newrelic-exporter:0.0.5
    command: ["./newrelic_exporter", "--newrelic.api-key=<NEWRELIC_API_KEY>"]
    ports:
    - containerPort: 9112
    volumeMounts:
    - name: config-volume
      mountPath: /config.yml
      subPath: config.yml
  volumes:
  - name: config-volume
    configMap:
      name: newrelic-exporter-config